### PR TITLE
New header image, adhering to Sunrise Style Guide

### PR DESCRIPTION
**Pull request by alxmrs**
View the preview at [https://sunrisebayarea.org/dev/](https://sunrisebayarea.org/dev/). 
Please let me know if this works well on all devices and / or if there are further style changes. 

I plan on adding a Nav bar next, in adherence to https://github.com/sunrise-bay-area/sunrise-bay-area/issues/16

### CODE REVIEW

**Review by marielagl — COMMENTED** [review]
Hey! Thanks so much for working on this! Already transforms our visual messaging so well.
The specific things I have to say about this issue is:

- that the splash image should be uploaded without any further editing. 

- In this instance the text shouldn't be responsive because the text placement moves and it makes the image less impactful, so I'd just have to edit the text into the image and upload it that way. Here's an example of what I mean with the splash image on Extinction Rebellion's site [https://rebellion.earth/](url)

- The font to be used in the tagline is actually Source Sans 'Black' not the 'Bold' typeface, and I changed the size of the lower line by 2 sizes down so that it would align better. There's also some spacing fixes.

I'd also remove the blur box from the back of the text.

I know there's a bunch of super specific style details, I'm a designer I can't help it 😅

I'll follow up with you on Slack!

**Comment by brookeangel** [comment]
> In this instance the text shouldn't be responsive because the text placement moves and it makes the image less impactful, so I'd just have to edit the text into the image and upload it that way. Here's an example of what I mean with the splash image on Extinction Rebellion's site https://rebellion.earth/

**Review by brookeangel — APPROVED** [review]
From the code side, this looks great to me (once Mariela's issues are addressed)!

Perhaps we could save uploading an image for a future PR, if at all? I'm not sure that having the text not be responsive would be as easy as with the Extinction Rebellion site, since a detailed image like this would be less SVG-able and might look kind of strange when scaled. (Also, the main sunrisemovement.org page has responsive text, so this is in-keeping with our styleguide still)

**Comment by marielagl** [comment]
> From the code side, this looks great to me (once Mariela's issues are addressed)!
> 
> Perhaps we could save uploading an image for a future PR, if at all? I'm not sure that having the text not be responsive would be as easy as with the Extinction Rebellion site, since a detailed image like this would be less SVG-able and might look kind of strange when scaled. (Also, the main sunrisemovement.org page has responsive text, so this is in-keeping with our styleguide still)

Ok, no worries about the text :)

**Comment by alxmrs** [comment]
> that the splash image should be uploaded without any further editing.

I have the original image added. I did this because is significantly simplified the styles. 
I can file an issue to fix this in the future, but I don't think this should block the new style for now.

**Comment by alxmrs** [comment]
> The font to be used in the tagline is actually Source Sans 'Black' not the 'Bold' typeface, and I changed the size of the lower line by 2 sizes down so that it would align better. There's also some spacing fixes.

Thank you! I'll update this now.

**Pull request merged**
